### PR TITLE
Add option to map the values of a prop with CSS-like syntax

### PR DESCRIPTION
**Pull request by Gejsi**
I noticed that mapping to prop values can be done only by using objects, so I decided to adapt it to a CSS-like syntax by passing another argument to the `styledMap` function. It came out something like this:
```js
styledMap('variant')`
  large: 2rem;
  small: 1em;
`
```

However, this solution would be a breaking change because if I wanted to write a normal `styledMap` I'd have to do this:
```js
styledMap()`
  large: 2rem;
  small: 1em;
`
```

#### My Solution
I renamed the main function to `styledMapFor` that accepts the extra argument and `styledMap` simply calls this function with a default value.
This maps values from the prop 'variant':
```js
styledMapFor('variant')`
  large: 2rem;
  small: 1em;
`
```
This maps the props:
```js
styledMap`
  large: 2rem;
  small: 1em;
`
```

> Note: I'm not really sure if `styledMapFor` is the most appropriate name, if you have a better one write it.

#### What about using regular objects?
Objects can still be used but I think the library should stop supporting them.
```js
styledMap('variant', {
  primary: 'pink',
  secondary: 'red',
  info: 'blue',
  default: 'white',
})
```
```js
styledMap({
  primary: 'pink',
  secondary: 'red',
  info: 'blue',
  default: 'white',
})
```

### CODE REVIEW

**Comment by edkalina** [comment]
Why do you use `styledMapFor`? Why not `styledMap`:

```javascript
styledMap('variant')`
  primary: pink;
  secondary: red;
  default: white;
`
```

**Comment by Gejsi** [comment]
As I already said, this would be a breaking change because if you want to create a normal `styledMap` you would have to write: 
```js
styledMap()`
  primary: pink;
  secondary: red;
  default: white;
`
```
Therefore, all the code written with the current version and before wouldn't work.

**Comment by scf4** [comment]
@Gejsi I don't see any reason why a breaking change will be necessary. The function can just detect whether template literals are being used or not. 

Thank you for opening the PR btw.

**Comment by scf4** [comment]
The styledMap function can handle f(p)\`\` in addition to f\`\`, f(o) and f(p, o) as it already does.

**Cases**

1. f\`\`
2. f(p)\`\`
3. f(o)
4. (p, o)


So the main function could work something like this:

```js
function (...args) {

  if (Array.isArray(args[0])) {
    handleCase1(args);
  }

  if (args.length === 1 && typeof args[0] === 'string') {
    handleCase2(args);
  }

  if (typeof args[0] === 'object') {
    handleCase3(args);
  } 

  if (args.length === 2 && typeof args[0] === 'string') {
    handleCase4(args);
  }
}

function handleCase1(stringArray, ...valArray) {
  // ...
};

function handleCase2(...args) {
  const prop = args[0];
  // Return function which handles template literals
  return (stringArray, ...valArray) => {
    // ...
  };
}

// etc...
```

The only issue is how to best write and organize it, avoiding code repetition.

**Comment by Gejsi** [comment]
@scf4 Ok, I see what you are trying to do. I can work on it if it's needed.

**Comment by edkalina** [comment]
I think it is already done in `styledMapFor`, so `styledMap` can be implemented like this:

```javascript
function styledMap(...args) {
  if (args.length === 1 && typeof args[0] === 'string') {
    return styledMapFor(args[0]);
  }

  return styledMapFor()(...args);
}
```

But probably it can be done in better way (in case of styles as object)

**Comment by Gejsi** [comment]
I refactored the code and now `styledMap` supports all use cases: tell me what you think about it. 👌

**Comment by scf4** [comment]
Hey, sorry for the late reply. I'll take another look at this soon!

**Comment by bitttttten** [comment]
Why should the library stop supporting object syntax?

**Comment by scf4** [comment]
@bitttttten I don't think there's a reason to stop supporting that syntax.

**Comment by scf4** [comment]
See README.md

**Pull request closed without merging**
