### PR TITLE
Support nested theme properties in mapToTheme()

### PR DESCRIPTION
**Pull request by macklinu**
Just came across this library and have found it very helpful. One thing that would allow me to use `mapToTheme()` would be to support nested object properties (my theme is a nested object, where the top level keys are namespaces):

```js
// theme.js

export default {
  colors,
  button: {
    foreground,
    background,
    border,
  },
  // etc.
}
```

Would you be open to adding the [dot-prop](https://github.com/sindresorhus/dot-prop) (or perhaps [get-value](https://github.com/jonschlinkert/get-value)) module as a dependency to support this feature request?

Thank you! 🙂

### CODE REVIEW

**Comment by scf4** [comment]
Hi @macklinu, thanks for the PR. I wanted to take a look at the dot-prop and get-value packages before responding.

Is there any reason to use dot-prop over get-value? It looks like get-value is slightly smaller and doesn't have any extra dependencies of its own, and we don't need to set props, so I think it would be the best option.

**Comment by macklinu** [comment]
Hi @scf4, sorry for the delay, but I've updated the commit to use get-value over dot-prop. Thanks for taking a look and let me know if this is 👍  or if I can make any changes. 😄

**Comment by scf4** [comment]
Thanks @macklinu, looks good. I'll have time to test and merge this weekend!

**Comment by scf4** [comment]
This functionality has been added in 3.1.0-beta

**Pull request closed without merging**
